"""Add document_cache table

Revision ID: b896cee64be4
Revises: cb1a701843c2
Create Date: 2026-09-06 20:27:31.126053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b896cee64be4'
down_revision: Union[str, Sequence[str], None] = 'cb1a701843c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_userId'), table_name='accounts')
    op.drop_constraint(op.f('uq_accounts_provider'), 'accounts', type_='unique')
    op.drop_index(op.f('ix_session_outputs_fileRecordId'), table_name='session_outputs')
    op.drop_index(op.f('ix_sessions_userId'), table_name='sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sessions_userId'), 'sessions', ['userId'], unique=False)
    op.create_index(op.f('ix_session_outputs_fileRecordId'), 'session_outputs', ['fileRecordId'], unique=False)
    op.create_unique_constraint(op.f('uq_accounts_provider'), 'accounts', ['provider', 'providerAccountId'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_accounts_userId'), 'accounts', ['userId'], unique=False)
    # ### end Alembic commands ###
